name: Build YARA and Test

on: [ push, pull_request ]

jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pkgs
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install wget ca-certificates build-essential bison flex automake autoconf libtool pkg-config

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.0

    - name: Print environment info
      run: |
        pwd
        env
        go version
        gcc --version

    - name: Build YARA
      run: |
        YARA_VERSION=4.3.1
        wget --no-verbose -O- https://github.com/VirusTotal/yara/archive/v${YARA_VERSION}.tar.gz | tar -C .. -xzf -
        ( cd ../yara-${YARA_VERSION} && ./bootstrap.sh )
        mkdir -p ../yara-build
        ( cd ../yara-build && \
          ../yara-${YARA_VERSION}/configure --disable-shared --prefix=${HOME}/prefix )
        make -C ../yara-build install
        find ${HOME}/prefix

    - name: Run Test
      run: |
        export PKG_CONFIG_PATH=${HOME}/prefix/lib/pkgconfig
        go test -v -tags yara_static ./...